### ISSUE TITLE
Buying resources not working

### ISSUE THREAD

**Issue by speedyconzales** [Heimdall-Industries/Heidrun#6]
It does not automatically buy the needed resources to refill my fleet. Instead it does claim atlas over and over again -> producing unnecessary transactions on the blockchain. 

Proposal: 

1. Fix the "buying resources" part of the code.
2. Check atlas balance of account before claiming atlas to prevent unnecessary transactions.

**Comment by MartinGerritsen** [comment]
Thank you Speedy, was this because you didn't have enough ATLAS?

**Comment by speedyconzales** [comment]
ATLAS was sufficient. Had to buy resources manually. Cannot provide any error messages. There were none. It just didn’t buy resources, but tried to refill fleet. At that point I got the „insufficient funds“ error because of the missing resources.

**Comment by MartinGerritsen** [comment]
![image](https://user-images.githubusercontent.com/861346/200823238-a1dec2f3-52cc-40c3-b638-f64c60e1b6a1.png)
https://github.com/Heimdall-Industries/Heidrun/pull/8
Updating the factory package seems to have fixed it

**Comment by speedyconzales** [comment]
I will try the new version. Never saw the output String: „RESOURCE ORDER COMPLETED: <resource_name>“
But I saw the next one: „Resources bought, resupplying“
So in my case, something in between wasn’t working correctly.

**Comment by MartinGerritsen** [comment]
Yes the orders were not working well, but that didn't stop the script from continuing 0_o
